"""add refresh token hash to users

Revision ID: c04b511e060b
Revises: dcb997bcc806
Create Date: 2026-01-02 18:36:24.263865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c04b511e060b'
down_revision: Union[str, Sequence[str], None] = 'dcb997bcc806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token_hash', sa.String(length=255), nullable=True))
    op.drop_constraint(op.f('uq_users_google_id'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=False)
    op.create_unique_constraint(op.f('uq_users_google_id'), 'users', ['google_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'refresh_token_hash')
    # ### end Alembic commands ###
